// Initial seed data parsed from the sample lesson document. Pastor
// runs the seed via the "Seed initial roster" / "Seed Possible Future
// Topics" / "Seed Past Topics" buttons on the empty-state of each
// page. Seed is idempotent (case-insensitive dedupe inside the
// bulkCreate helpers) so re-running is safe.

// 46 names, first-name-only, alphabetical by first letter. Disambiguators
// (B/H, B/M) baked into the display name where the same first name
// appears more than once.
export const SEED_ROSTER = [
  'Andretti',
  'Anna',
  'Anne Marie',
  'Arubra',
  'Betty',
  'Carla',
  'Carole',
  'Carter',
  'Chris',
  'Cindy',
  'Connie',
  'Cynthia B',
  'Cynthia H',
  'Debbie',
  'Donna',
  'Doris',
  'Everett',
  'Evelyn',
  'Ginga',
  'Ira',
  'Ivan',
  'Jack',
  'Janice',
  'Jesse',
  'Jon Tal',
  'Joyce',
  'Karen',
  'Kathy B',
  'Kathy M',
  'Kenny',
  'Kyle',
  'Laura',
  'Marlene',
  'Millie',
  'Nerrick',
  'Paige',
  'Sammie',
  'Sarah',
  'Savannah',
  'Shelia',
  'Steve',
  'Todd',
  'Trude',
  'Tyler',
  'Wallace',
  'Wayne',
];

// 60 possible-future topics in the order they appeared in the sample doc.
export const SEED_POSSIBLE_FUTURE = [
  'Explore the concepts of vertical and horizontal morality, and how they relate to being a Christian',
  'How should Christians think about ambition?',
  'When does helping someone become enabling?',
  'How do we handle moral gray areas?',
  'Is it possible to love your neighbor and still strongly disagree?',
  'What does truly look like in practice?',
  'What is the purpose of the church today?',
  'What makes a church feel spiritually alive?',
  'How do we measure faithfulness vs. success?',
  'What role should tradition play in shaping worship?',
  'How do we welcome without losing identity?',
  'What does meaningful membership look like?',
  'How do churches handle disagreement well?',
  'What is the difference between church and community?',
  'What does faithfulness look like in a digital age?',
  'How should Christians think about environmental responsibility?',
  'Is progress always good?',
  'What does it mean to be human in an age of technology?',
  'How do we stay grounded in a distracted culture?',
  "What is the church's role in shaping culture?",
  'How should Christians engage with conspiracy thinking?',
  'What does hope look like in uncertain times?',
  'Can institutions still carry spiritual authority?',
  'How do we live faithfully in a pluralistic society?',
  'If you could witness one biblical moment in person, which would it be?',
  'If Jesus came today, what might surprise him most?',
  'What metaphor best describes your faith right now?',
  "What would a parable for today's world sound like?",
  'If your life had a spiritual soundtrack, what song is playing now?',
  "What is one belief you've changed your mind about—and why?",
  'What question do you wish someone would ask you about faith?',
  'If God is relational, can God be lonely?',
  'Does God experience time the way we do?',
  'What would it mean for God to risk something?',
  'Can God be surprised?',
  'Is God more like a parent, partner, or presence?',
  'Does God need us for anything?',
  'What does it mean to say God is "personal" but not a person?',
  'Can we choose God, or are we chosen?',
  'Is divine silence a form of communication?',
  'What would it mean for God to grow?',
  'How would the Bible read differently if written today?',
  'What does it mean to read Scripture faithfully vs. literally?',
  'Which biblical characters are misunderstood—and why?',
  'What stories in Scripture feel unresolved or unfinished?',
  'How do we handle passages that trouble us?',
  'What role does tradition play in reading the Bible?',
  'What questions does the Bible not answer?',
  'How does translation shape theology more than we realize?',
  'What does it mean that Scripture is both human and divine?',
  'What does a healthy spiritual life actually look like?',
  'Can you outgrow certain forms of faith practice?',
  'What is the role of doubt in spiritual maturity?',
  'How do we pray when we feel nothing?',
  'What spiritual habits harm rather than help?',
  'What does it mean to rest spiritually?',
  'Can busyness be a spiritual issue?',
  'What does it look like to trust God without certainty?',
  'How do we discern between conviction and guilt?',
  'What does abiding in God practically mean?',
  'Is it ever right to cut someone out of your life?',
  'What does Christian love look like in conflict?',
  'How do we balance honesty and kindness?',
  'What is the difference between forgiveness and reconciliation?',
];

// Past topics from the sample doc. "(article)" suffixes preserved
// verbatim — that's metadata the pastor wants visible, not promoted
// to a separate column.
export const SEED_PAST_TOPICS = [
  'Can God make a race car so fast that God cannot beat it in a race?',
  'If you could talk to anyone who is dead, who would it be and what would you ask them?',
  "Is it justifiable for God to curse humanity for one or two people's mistake?",
  'If God is "cupcakes and rainbows," then why does God give us the ability to give into sin?',
  'How does that belief/nonbelief relate to the Christian faith?',
  '"Heal the River" documentary',
  'If heaven is all good and hell is all bad, do we lose our free will in either destination?',
  "How can I be an answer to someone else's prayer",
  'Spaghetti Marshmallow Challenge',
  'How would today be different if you knew it was your last day?',
  'Petitionary prayer',
  'What is heaven like? Is heaven personalized for you when you go there?',
  'What do you think happens when you die? When do you go to heaven — immediately or when Jesus comes? | Is there a purgatory and what will it do different than heaven?',
  'Can you swear $@! In heaven?',
  'Do you often have an "ah ha" moment and think, wow, that was God?',
  'Can you touch God?',
  'How much of our life is predetermined?',
  'What is Christian Nationalism? And is it Christian?',
  'Who created God?',
  'What should our Sunday schedule be?',
  "What does it mean to be \"made in God's image\"?",
  'Could you walk on water in a storm to meet Jesus?',
  'Are there animals in heaven?',
  'Can God or Jesus actually speak to you?',
  'Creation, Big Bang or Other',
  'Can you argue with God?',
  'Non-canonical Books of the Bible',
  'Can you have enemies in heaven?',
  'Atonement Theories',
  'What would be a real-life example of a miracle — and not just a happy coincidence?',
  'How was the world so populated by the time of the flood?',
  'Does God ever change? (article)',
  'When does conflict become spiritual abuse? (article)',
  'Autism & the Church (article)',
  'Disability Theology? (article)',
  'Why did God create earth round?',
  'How did Jesus find men in the Middle East named Matthew, Mark, Luke, and John?',
  'How do you know if the Holy Spirit is working in your life? How to ID a "spirit filled" church?',
  'Why did David pick up 5 stones?',
  'Is life flashing before your eyes real? Literal?',
  'Indubitability',
  'Why did God create man?',
  'How do I know if anyone is godly? (article)',
  'What is the significance of 40 days and nights in the Bible?',
  'If you could physically touch God, what would happen?',
  'Creationism?',
  'Hidden World of Prayer',
  'What would you do if someone knocked on your door and said they were Jesus?',
  'Does God hear the prayers of non-believers?',
  'Where is God in times of natural disaster? (article)',
  'If God loves us, why are we told to fear God?',
  'Will we see loved ones in heaven?',
  'Was it nice of Jesus to curse the fig tree?',
  'What does "God\'s Will" really mean?',
  'Deism and the Founding Fathers',
  "What's up with Matthew 10:32-39?",
  'How do we "Forgive those who trespass against us?"',
  'Suicide',
  'Does the Bible support slavery?',
  'Are young people really going to church less? Why?',
  'How do you know when God is answering prayer?',
  'What is the difference between Methodists and Episcopalians?',
  'What should I say to someone who is grieving?',
  'Is death inherently bad?',
  'Who is Bart Ehrman and what is unique about his perspective regarding the Bible?',
  'What does the Bible really mean by "eye for an eye"? (article)',
  'What is the most misinterpreted Bible passage? (article)',
  'Should there be a separation of church and state? (article)',
  'Character Alignment Chart and the Bible',
  'Should churches pay taxes if they want a say in political actions?',
  'What does your Scripture say about love?',
  'How can there be a God in such a chaotic world? (article)',
  'Does God present Himself physically to anyone? (article)',
  'How do dreams and visions relate to our understanding of God?',
  'Will we see our loved ones in heaven?',
  'How would Christians approach the topic of mental health?',
  'What is the Christian view of reincarnation?',
  'The concept of luck',
  'What are we to make of telepathy?',
  'AI and Christianity',
  'The Trinity',
  'Jesus in the Old Testament',
  'What does the Bible say about extra-terrestrial life?',
  'Are there levels or degrees of sin?',
  'How do current events line up with Biblical prophecies?',
  'The Documentary Hypothesis',
  'Is God male?',
  "Do all good people go to heaven even if they don't believe in Jesus?",
  'Israel/Palestine conflict',
  'Why do bad people prosper?',
  'What do different denominations believe about speaking in tongues?',
  'Can you be a Christian nationalist?',
  "What's up with Paul? (Seems self-centered, issues with women, homosexuals — Jesus did not)",
  "Does prayer change God's mind or our perspective?",
  'What is millennialism and its varieties? What are arguments for and against?',
  'What is the future of the UMC?',
  'Are virtually all wars due to religious difference?',
  'Are there discrepancies in the gospels? If so, why?',
  'How should Christians view the phenomenon of near-death experience?',
  'Should we teach the 10 Commandments in school? (article)',
  'Should flags be displayed in houses of worship? (article)',
  'Would God forgive a serial killer? Is there such thing as an unforgiveable sin?',
  'Does God take attendance?',
  'What is Progressive Christianity? How does it compare with earlier liberalism?',
  'Dreams: What do they tell us?',
  'What is up with all the different versions of the Bible?',
  "Once we've made a decision, how do we know if it was the will of God?",
  'What does the Bible say about economics?',
  'Churches in Revelation 2 & 3',
  "Have you ever been so overwhelmed that you can't pray to God?",
  'What is sin?',
  'Stages of Faith',
  'Cremation',
  'Does God like Christofacism?',
  'What happens to people who died before Christ',
  'What was the Jewish and Christian understanding of heaven in the 1st century?',
  'Where did Jesus learn to read?',
  'Arguments for/against the Sermon on the Mount',
  'How not to grow weary in the face of fear',
  'What does your faith say about capital punishment?',
  'What are your thoughts about assisted suicide for terminally ill patients?',
  'Are we alone in the universe?',
  'What is "allegorical" interpretation of the Bible?',
  'How do you know the voice of God?',
  'Will there be jobs in heaven?',
  'Will there be annoyances like saran wrap in heaven?',
  'What is the purpose of intercessory prayer if God is good, loving, powerful, and knows all?',
  'If Jesus knew that Judas was going to betray him, why did he let him be a disciple? (article)',
  'Why was slavery OK in biblical times — or was it? (article)',
  "How can we know for sure we've been forgiven? (article)",
  'Can bad money do good? (article)',
  'Pros and Cons of "Woke"',
  'Is suffering a punishment for sin? (article)',
  "Was Joseph, Jesus's earthly father, educated and able to teach Jesus?",
  'Should religion be taught in public schools? (article)',
  "What does it mean to be 'made in God's image'? (article)",
  "Do you believe in ghosts? Do you think the dead are still with us? (article)",
  "Is there a sin Jesus's blood doesn't wash away (article)",
  "How is it possible that God hears everyone's prayers? (article)",
  'What is one thing you remember from a previous Sunday School lesson?',
  'Can AI be a force for good and God? (article)',
  'When was Jesus actually born?',
  "What's up with the 12 Days of Christmas?",
  'What should Christians think of the concept of luck?',
  'If Jesus knew that Judas was going to betray him, why did he let him be a disciple? (Reprise)',
  'Will heaven be crowded or will we only be with our friends and family?',
  'Do people of other faiths have similar Near Death Experiences and afterlife imaginings? (2 Parts)',
  'What are the different theologies of communion across various traditions?',
  'What should we say to folks who quote the Bible about women not being pastors? (article)',
  'What parts of the Bible feel most culturally bound vs. timeless?',
  'Is God more like a parent, partner, or presence?',
  'Is it possible to love your neighbor and still strongly disagree?',
  'What does faith look like on an ordinary Tuesday?',
  'If you had to summarize your faith in one sentence, what would it be?',
  'Can we choose God or are we chosen?',
];
